repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1  # Use the latest version
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: end-of-file-fixer
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 22.3.0  # Use the latest version
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1  # Use the latest version
    hooks:
      - id: isort
        profile: black

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1  # Use the latest version
    hooks:
      - id: flake8

# Optionally, you can add MyPy for static type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910  # Use the latest version
    hooks:
      - id: mypy
