datasets:
    MNIST:
      img_width: 28
      img_height: 28
      num_channels: 1
    FashionMNIST:
      img_width: 28
      img_height: 28
      num_channels: 1
    CIFAR10:
      img_width: 32
      img_height: 32
      num_channels: 3

embedding_models:
  AutoEncoder:
    pretrained: true
  BYOL:
    pretrained: true
  EfficientNet:
    pretrained: true
  MobileNet:
    pretrained: true
